package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TOTAL_WH_ROUND_RESULT.
 */
public class TotalWhRoundResult {

    private Long WhRoundResultID;
    private String studentCode;
    private String gradeCode;
    private Integer sex;
    private String hItemCode;
    private String wItemCode;
    private Integer hResult;
    private Integer wResult;
    private Integer RoundNo;
    private String TestTime;
    private Integer ResultState;
    private String Mac;

    public TotalWhRoundResult() {
    }

    public TotalWhRoundResult(Long WhRoundResultID) {
        this.WhRoundResultID = WhRoundResultID;
    }

    public TotalWhRoundResult(Long WhRoundResultID, String studentCode, String gradeCode, Integer sex, String hItemCode, String wItemCode, Integer hResult, Integer wResult, Integer RoundNo, String TestTime, Integer ResultState, String Mac) {
        this.WhRoundResultID = WhRoundResultID;
        this.studentCode = studentCode;
        this.gradeCode = gradeCode;
        this.sex = sex;
        this.hItemCode = hItemCode;
        this.wItemCode = wItemCode;
        this.hResult = hResult;
        this.wResult = wResult;
        this.RoundNo = RoundNo;
        this.TestTime = TestTime;
        this.ResultState = ResultState;
        this.Mac = Mac;
    }

    public Long getWhRoundResultID() {
        return WhRoundResultID;
    }

    public void setWhRoundResultID(Long WhRoundResultID) {
        this.WhRoundResultID = WhRoundResultID;
    }

    public String getStudentCode() {
        return studentCode;
    }

    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    public String getGradeCode() {
        return gradeCode;
    }

    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getHItemCode() {
        return hItemCode;
    }

    public void setHItemCode(String hItemCode) {
        this.hItemCode = hItemCode;
    }

    public String getWItemCode() {
        return wItemCode;
    }

    public void setWItemCode(String wItemCode) {
        this.wItemCode = wItemCode;
    }

    public Integer getHResult() {
        return hResult;
    }

    public void setHResult(Integer hResult) {
        this.hResult = hResult;
    }

    public Integer getWResult() {
        return wResult;
    }

    public void setWResult(Integer wResult) {
        this.wResult = wResult;
    }

    public Integer getRoundNo() {
        return RoundNo;
    }

    public void setRoundNo(Integer RoundNo) {
        this.RoundNo = RoundNo;
    }

    public String getTestTime() {
        return TestTime;
    }

    public void setTestTime(String TestTime) {
        this.TestTime = TestTime;
    }

    public Integer getResultState() {
        return ResultState;
    }

    public void setResultState(Integer ResultState) {
        this.ResultState = ResultState;
    }

    public String getMac() {
        return Mac;
    }

    public void setMac(String Mac) {
        this.Mac = Mac;
    }

}
